# Generated by Django 5.1.2 on 2024-10-27 15:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цветовая гамма торта')),
            ],
            options={
                'verbose_name_plural': 'Цветовая гамма торта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Начинка')),
            ],
            options={
                'verbose_name_plural': 'Начинка',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Форма торта')),
            ],
            options={
                'verbose_name_plural': 'Форма торта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name_plural': 'Статус заказа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус наличия товара')),
            ],
            options={
                'verbose_name_plural': 'Статус наличия товара',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Количество ярусов торта (этажей)')),
            ],
            options={
                'verbose_name_plural': 'Количество ярусов торта (этажей)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Вес торта')),
            ],
            options={
                'verbose_name_plural': 'Вес торта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название города')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.country')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес торта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cakes/', verbose_name='Приложите фото торта, который вам нравится')),
                ('inscription', models.CharField(max_length=50, verbose_name='Надпись на торте')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена торта, сом')),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Предоплата 50%')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.color', verbose_name='Основная цветовая гамма')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.filling', verbose_name='Начинка')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.form', verbose_name='Форма торта')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.tier', verbose_name='Количество ярусов торта (этажей)')),
            ],
            options={
                'verbose_name_plural': 'Торты',
                'ordering': ['filling'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Магазины')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.city')),
            ],
            options={
                'verbose_name_plural': 'Магазины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=datetime.date(2024, 10, 27), verbose_name='Дата создания заказа')),
                ('date_ready', models.DateField(default=datetime.date(2024, 10, 27), verbose_name='Дата выдачи торта')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.cake')),
                ('order_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.orderstatus', verbose_name='Статус заказа')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.shop', verbose_name='Магазин для получения торта')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование ингредиента')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена,сом/кг')),
                ('quantity', models.IntegerField(verbose_name='Количество,кг')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cakes/')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.manufacturer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.status')),
            ],
            options={
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
    ]
