# Generated by Django 5.1.2 on 2024-10-27 16:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='cake',
            name='comments',
            field=models.CharField(default='', max_length=250, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='cake',
            name='date_create',
            field=models.DateField(default=datetime.date(2024, 10, 27), verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='cake',
            name='date_ready',
            field=models.DateField(default=datetime.date(2024, 10, 27), verbose_name='Дата выдачи торта'),
        ),
        migrations.AddField(
            model_name='cake',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cakes.shop', verbose_name='Магазин для получения торта'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
