# Generated by Django 5.1.2 on 2024-10-30 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_cake__status_cake_comments_cake_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='client_name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='cake',
            name='phone_number',
            field=models.CharField(default='', max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='date_create',
            field=models.DateField(default=datetime.date(2024, 10, 30), verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='date_ready',
            field=models.DateField(default=datetime.date(2024, 10, 30), verbose_name='Дата выдачи торта'),
        ),
    ]
