# Generated by Django 5.1.2 on 2024-10-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_cake_client_name_cake_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='_status',
            new_name='status',
        ),
    ]
