# Generated by Django 5.1.2 on 2024-11-03 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_rename__status_cake_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='color',
            field=models.CharField(default='', max_length=30, verbose_name='Основная цветовая гамма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='date_create',
            field=models.DateField(default=datetime.date(2024, 11, 3), verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='date_ready',
            field=models.DateField(default=datetime.date(2024, 11, 3), verbose_name='Дата выдачи торта'),
        ),
    ]
