# Generated by Django 5.1.2 on 2024-11-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_delete_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
