# Generated by Django 5.1.2 on 2024-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_delete_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='client',
            field=models.TextField(default='', verbose_name='Заказчик'),
        ),
    ]
