# Generated by Django 5.1.2 on 2024-11-04 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_cake_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='date_create',
            field=models.DateField(default=datetime.date(2024, 11, 4), verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='date_ready',
            field=models.DateField(default=datetime.date(2024, 11, 4), verbose_name='Дата выдачи торта'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cakes/', verbose_name='Приложите фото торта, который вам нравится'),
        ),
    ]
